import React,{useMemo,useState} from 'react'
import {CalendarDays,MapPin,Users,Trophy,ChevronRight,Search,Menu,X,Clock3,Lock} from 'lucide-react'
import data from './realData'
import logo from './nngg-logo.png'

const nav=[['Inicio','inicio'],['Sedes','sedes'],['Equipos','equipos'],['Gran final','final']]
const blocks=[
 {title:'3 Y 4 DE OCTUBRE',topic:'¿Es el sistema público de pensiones sostenible a largo plazo?',names:['Valencia','Zaragoza','Granada','Murcia','Oviedo','Palma de Mallorca','Vitoria-Gasteiz']},
 {title:'8, 10 Y 11 DE OCTUBRE',topic:'¿Deben las Administraciones Públicas priorizar la vivienda pública o la inversión privada?',names:['Madrid','Barcelona','Sevilla','Salamanca','Santiago','Las Palmas de Gran Canaria']}
]
function daysLeft(d){return Math.max(0,Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000))}
function venueDate(c){if(c.date==='2026-10-08')return'8 de octubre';if(c.date==='2026-10-10')return'10 de octubre';if(c.date==='2026-10-11')return'11 de octubre';if(c.date==='2026-10-04')return'4 de octubre';return'3 de octubre'}
function App(){const[page,setPage]=useState('inicio');const[mobile,setMobile]=useState(false);return <div className="app"><header className="topbar"><button className="brand" onClick={()=>setPage('inicio')}><img src={logo}/><span><strong>III TORNEO NACIONAL DE DEBATE</strong><small>NNGG ESPAÑA · 2026</small></span></button><nav className="desktopnav">{nav.map(([l,k])=><button className={page===k?'active':''} key={k} onClick={()=>setPage(k)}>{l}</button>)}</nav><button className="mobilebtn" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>{mobile&&<div className="mobilenav">{nav.map(([l,k])=><button key={k} onClick={()=>{setPage(k);setMobile(false)}}>{l}</button>)}</div>}<main>{page==='inicio'&&<Home go={setPage}/>} {page==='sedes'&&<Venues/>} {page==='equipos'&&<Teams/>} {page==='final'&&<Final/>}</main><footer><img src={logo}/><span>III Torneo Nacional de Debate</span><small>NNGG España · 2026</small></footer></div>}
function Home({go}){return <><section className="hero"><div className="flagline"><i></i><b></b><i></i></div><img className="herologo" src={logo}/><div className="kicker">NNGG ESPAÑA PRESENTA</div><h1>III Torneo Nacional<br/><em>de Debate</em></h1><p className="lead">Una competición de <strong>debate académico</strong> para formarnos, competir y poner en valor el talento de nuestra organización.</p><div className="heroactions"><button className="primary" onClick={()=>go('sedes')}>Ver sedes <ChevronRight size={18}/></button><button className="secondary" onClick={()=>go('equipos')}>Ver equipos</button></div></section><section className="deadline"><div className="deadlineicon"><Clock3/></div><div><span>INSCRIPCIONES</span><strong>27 de septiembre</strong><small>Último día para inscribir a tu equipo</small></div><div className="count"><strong>{daysLeft('2026-09-27')}</strong><span>días</span></div></section><section className="stats"><Stat icon={<MapPin/>} n="13" label="Sedes clasificatorias"/><Stat icon={<CalendarDays/>} n="3–11 oct" label="Fase clasificatoria"/><Stat icon={<Users/>} n={String(data.teams.length)} label="Equipos inscritos"/><Stat icon={<Trophy/>} n="24 oct" label="Gran final · Madrid"/></section><section className="finalbanner"><div><span>24 OCTUBRE · MADRID</span><h2>La gran final</h2><p>16 equipos finalistas competirán en una única jornada.</p></div><button onClick={()=>go('final')}>Gran final <ChevronRight/></button></section></>}
function Venues(){const map=Object.fromEntries(data.cities.map(c=>[c.name,c]));return <section className="section page"><SectionTitle eyebrow="FASE CLASIFICATORIA" title="13 sedes · 2 temas"/><p className="intro">Cada equipo compite en la sede elegida en su inscripción. El tema depende de la fecha de su fase clasificatoria.</p>{blocks.map(b=><div key={b.title}><h3 className="dateheading">{b.title}</h3><div className="topicCallout">{b.topic}</div><div className="citygrid">{b.names.map(name=>{const c=map[name];return <div className="citycard" key={name}><span>{String(c.id).padStart(2,'0')}</span><MapPin size={19}/><h3>{name}</h3><p>{venueDate(c)}</p><div className="venuePills"><small className="venuePill"><Users size={13}/>{c.registered} {c.registered===1?'equipo':'equipos'}</small><small className="lockedPill"><Lock size={12}/>Consultar finalistas</small></div></div>})}</div></div>)}</section>}
function Teams(){const[q,setQ]=useState('');const[city,setCity]=useState('Todos');const cities=['Todos',...new Set(data.teams.map(t=>t.city))];const list=useMemo(()=>data.teams.filter(t=>(city==='Todos'||t.city===city)&&(t.name+' '+t.city).toLowerCase().includes(q.toLowerCase())),[q,city]);return <section className="section page"><SectionTitle eyebrow="INSCRIPCIONES" title="Equipos"/><p className="intro">Conoce los equipos que participan en el torneo.</p><div className="teamSummary"><div><Users size={20}/><strong>{data.teams.length}</strong><span>equipos inscritos</span></div><div><MapPin size={20}/><strong>13</strong><span>sedes</span></div><button className="finalistsLocked" disabled><Trophy size={17}/>Consultar finalistas <Lock size={14}/></button></div><div className="teamTools"><div className="searchbox"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar equipo o sede"/></div><div className="cityFilters">{cities.map(c=><button key={c} className={city===c?'selected':''} onClick={()=>setCity(c)}>{c}</button>)}</div></div><div className="teamgrid">{list.map(t=><div className="teamcard" key={t.id}><div className="teammark">{t.name.slice(0,2).toUpperCase()}</div><div className="teamInfo"><h3>{t.name}</h3><div className="teamMeta"><span className="cityTag"><MapPin size={13}/>{t.city}</span><span><Users size={14}/>{t.participants} participantes</span></div></div></div>)}</div><p className="privacyNote">No se publican datos personales de los participantes.</p></section>}
function Final(){const finalists=Array.from({length:16},(_,i)=>data.finalists?.[i]||null);return <section className="section page finalPage"><SectionTitle eyebrow="24 OCTUBRE · MADRID" title="Gran final"/><div className="finalHero"><div className="finalHeroIcon"><Trophy/></div><div><span>GRAN FINAL</span><h3>16 equipos finalistas</h3><p>Los clasificados se irán mostrando a medida que queden confirmados.</p></div></div><div className="finalistsBoard"><div className="finalistsHeader"><div><span>CLASIFICADOS</span><h3>Finalistas</h3></div><strong>{data.finalists?.length||0}<small>/16</small></strong></div><div className="finalistGrid">{finalists.map((team,i)=>team?<div className="finalistSlot unlocked" key={i}><div className="finalistCircle">{team.name.slice(0,2).toUpperCase()}</div><strong>{team.name}</strong><small>{team.city||''}</small></div>:<div className="finalistSlot" key={i}><div className="finalistCircle">?</div><strong>Finalista {i+1}</strong><small>Por confirmar</small></div>)}</div></div><div className="finalTopic"><span>TEMA DE LA GRAN FINAL</span><strong>Se anunciará el 11 de octubre</strong></div><div className="finalslot"><span>MADRID · 24 OCT</span><Trophy size={30}/><strong>GRAN FINAL</strong><small>Una única jornada</small></div></section>}
function SectionTitle({eyebrow,title}){return <div className="sectiontitle"><span>{eyebrow}</span><h2>{title}</h2></div>}
function Stat({icon,n,label}){return <div className="stat"><span>{icon}</span><strong>{n}</strong><small>{label}</small></div>}
export default App
