import React,{useMemo,useState} from 'react'
import {CalendarDays,MapPin,Users,Trophy,ChevronRight,Search,Menu,X,Clock3} from 'lucide-react'
import data from './realData'
import logo from './nngg-logo.png'

const nav=[['Inicio','inicio'],['Sedes','sedes'],['Equipos','equipos'],['Gran final','final']]
const blocks=[
 {title:'3 Y 4 DE OCTUBRE',topic:'¿Es el sistema público de pensiones sostenible a largo plazo?',names:['Valencia','Zaragoza','Granada','Murcia','Oviedo','Palma de Mallorca']},
 {title:'8, 10 Y 11 DE OCTUBRE',topic:'¿Deben las Administraciones Públicas priorizar la vivienda pública o la inversión privada?',names:['Madrid','Barcelona','Sevilla','Salamanca','Santiago','Vitoria-Gasteiz','Las Palmas de Gran Canaria']}
]
function daysLeft(d){return Math.max(0,Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000))}
function App(){const[page,setPage]=useState('inicio');const[mobile,setMobile]=useState(false);return <div className="app">
<header className="topbar"><button className="brand" onClick={()=>setPage('inicio')}><img src={logo}/><span><strong>III TORNEO NACIONAL DE DEBATE</strong><small>NNGG ESPAÑA · 2026</small></span></button><nav className="desktopnav">{nav.map(([l,k])=><button className={page===k?'active':''} key={k} onClick={()=>setPage(k)}>{l}</button>)}</nav><button className="mobilebtn" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
{mobile&&<div className="mobilenav">{nav.map(([l,k])=><button key={k} onClick={()=>{setPage(k);setMobile(false)}}>{l}</button>)}</div>}
<main>{page==='inicio'&&<Home go={setPage}/>} {page==='sedes'&&<Venues/>} {page==='equipos'&&<Teams/>} {page==='final'&&<Final/>}</main>
<footer><img src={logo}/><span>III Torneo Nacional de Debate</span><small>NNGG España · 2026</small></footer></div>}
function Home({go}){return <><section className="hero"><div className="flagline"><i></i><b></b><i></i></div><img className="herologo" src={logo}/><div className="kicker">NNGG ESPAÑA PRESENTA</div><h1>III Torneo Nacional<br/><em>de Debate</em></h1><p className="lead">Una competición de <strong>debate académico</strong> para formarnos, competir y poner en valor el talento de nuestra organización.</p><div className="heroactions"><button className="primary" onClick={()=>go('sedes')}>Ver sedes <ChevronRight size={18}/></button><button className="secondary" onClick={()=>go('equipos')}>Ver equipos</button></div></section>
<section className="deadline"><div className="deadlineicon"><Clock3/></div><div><span>INSCRIPCIONES</span><strong>27 de septiembre</strong><small>Último día para inscribir a tu equipo</small></div><div className="count"><strong>{daysLeft('2026-09-27')}</strong><span>días</span></div></section>
<section className="stats"><Stat icon={<MapPin/>} n="13" label="Sedes clasificatorias"/><Stat icon={<CalendarDays/>} n="3–11 oct" label="Fase clasificatoria"/><Stat icon={<Users/>} n={String(data.teams.length)} label="Respuestas recibidas"/><Stat icon={<Trophy/>} n="24 oct" label="Gran final · Madrid"/></section>
<section className="finalbanner"><div><span>24 OCTUBRE · MADRID</span><h2>La gran final</h2><p>16 equipos finalistas competirán en una única jornada.</p></div><button onClick={()=>go('final')}>Gran final <ChevronRight/></button></section></>}
function Venues(){const map=Object.fromEntries(data.cities.map(c=>[c.name,c]));return <section className="section page"><SectionTitle eyebrow="FASE CLASIFICATORIA" title="13 sedes · 2 temas"/><p className="intro">Cada equipo compite en la sede elegida en su inscripción. El tema depende de la fecha de su fase clasificatoria.</p>{blocks.map(b=><div key={b.title}><h3 className="dateheading">{b.title}</h3><div className="topicCallout">{b.topic}</div><div className="citygrid">{b.names.map(name=>{const c=map[name];return <div className="citycard" key={name}><span>{String(c.id).padStart(2,'0')}</span><MapPin size={19}/><h3>{name}</h3><p>{c.date==='2026-10-08'?'8 de octubre':c.date==='2026-10-10'?'10 de octubre':'3/4 de octubre'}</p><small>{c.registered} equipos confirmados · {c.finalistSlots} {c.finalistSlots===1?'plaza':'plazas'} para la final</small></div>})}</div></div>)}</section>}
function Teams(){const[q,setQ]=useState('');const list=useMemo(()=>data.teams.filter(t=>(t.name+' '+t.city).toLowerCase().includes(q.toLowerCase())),[q]);return <section className="section page"><SectionTitle eyebrow="INSCRIPCIONES" title="Equipos"/><p className="intro">Datos reales de inscripción. No se publican datos personales de los participantes.</p><div className="searchbox"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar equipo o sede"/></div><div className="teamgrid">{list.map(t=><div className="teamcard" key={t.id}><div className="teammark">{t.name.slice(0,2).toUpperCase()}</div><div><h3>{t.name}</h3><p><MapPin size={14}/>{t.city}</p><small>{t.participants} participantes</small></div><div className="teamstats"><span><b>{t.status}</b></span></div></div>)}</div></section>}
function Final(){return <section className="section page"><SectionTitle eyebrow="24 OCTUBRE · MADRID" title="Gran final"/><div className="finalintro"><Trophy/><div><h3>16 equipos finalistas</h3><p>Los clasificados se mostrarán aquí cuando queden confirmados.</p></div></div><div className="emptyfinal"><Trophy/><strong>Tema de la gran final</strong><span>Se anunciará el 11 de octubre.</span></div><div className="finalslot"><span>MADRID · 24 OCT</span><Trophy size={30}/><strong>GRAN FINAL</strong><small>Una única jornada</small></div></section>}
function SectionTitle({eyebrow,title}){return <div className="sectiontitle"><span>{eyebrow}</span><h2>{title}</h2></div>}
function Stat({icon,n,label}){return <div className="stat"><span>{icon}</span><strong>{n}</strong><small>{label}</small></div>}
export default App
